apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  DB_PASSWORD: "sensitive-data-in-configmap"  
  PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEpQIBAAKCAQEA...
    -----END PRIVATE KEY-----