name: Infrastructure Validation
on:
  pull_request:
    paths:
        - 'project/gh-action/**'
    branches:
        - 'gh-action-testing/**'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: project/gh-action/infrastructure/kubernetes
    steps:
      - uses: actions/checkout@v4
      
      - name: Install kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo cp kubeval /usr/local/bin
      
      - name: Validate K8s manifests
        run: kubeval *.yaml

  terraform:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: project/gh-action/infrastructure/terraform
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Validate Terraform
        run: |
          terraform init
          terraform validate